name: twitter_auto_like_by_query

# トリガーイベント
on:
  # 1. main ブランチへのプッシュ: 通知がうざいから停止中
  # push:
  #   branches:
  #     - main
  # 2. GitHub 上の手動実行
  workflow_dispatch:
  # 3. crontab
  schedule:
    # 1 時間毎
    - cron: "00 * * * *"

jobs:
  twitter_auto_like_by_query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run twitter_auto_like_by_query.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: python twitter_auto_like_by_query.py
